---
# Join worker nodes to the cluster

- name: Join Worker | Get join command from first master
  ansible.builtin.set_fact:
    join_cmd: "{{ hostvars['localhost']['kubeadm_join_command'] }}"

- name: Join Worker | Join cluster as worker
  ansible.builtin.command: "{{ join_cmd }}"
  register: join_result
  changed_when: join_result.rc == 0
